# Generated by Django 3.2.7 on 2021-10-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('credit', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_name', models.TextField(max_length=200)),
                ('comm_about', models.TextField(default='Welcome to the Community', max_length=2000)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('comm_url', models.URLField(blank=True)),
                ('comm_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authuser.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.TextField(max_length=200)),
                ('post_text', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('post_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authuser.profile')),
                ('post_on_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.community')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.comment')),
                ('vote_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.post')),
                ('vote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.profile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='on_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.post'),
        ),
    ]
