# Generated by Django 3.2.7 on 2021-10-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='downvote',
            new_name='credit',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote',
        ),
    ]
