# Generated by Django 3.2.7 on 2021-10-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='comm_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=60),
        ),
    ]
